export const GLOBAL_SHOW_LOADING = 'GLOBAL_SHOW_LOADING'
export const GLOBAL_HIDE_LOADING = 'GLOBAL_HIDE_LOADING'
export const GLOBAL_SHOW_TOAST = 'GLOBAL_SHOW_TOAST'
export const GLOBAL_HIDE_TOAST = 'GLOBAL_HIDE_TOAST'